### ISSUE TITLE
Formatting of shared content not consistent with other formatting

### ISSUE THREAD

**Issue by kingemir** [saiwal/Utsukta-hub-themes#19]
After sharing a post (which creates a new post with me as author), the formatting of the shared content is not consistent with the formatting of other text (fontcolor, background color etc). Bright text on bright background is not readable.

**Comment by kingemir** [comment]
I use brite. 

Here's an example post containing shared content: https://labonneheure.ch/item/b4804800-c145-4dfa-9f4e-5e74def6b5ee
<img width="660" height="592" alt="Image" src="https://github.com/user-attachments/assets/f854d688-2306-48ea-82e4-819c57ef5106" />

While normal links (i.e. Ema エマ in the screenshot) are 
`color: rgba(var(--bs-link-color-rgb), var(--bs-link-opacity, 1)); font-weight: bold !important; font-size: var(--bs-body-font-size);`
links within the shared content (i.e. UrsuUrsula) are 
`color: var(--bs-info); font-weight: 500; font-size: 0.95rem;`

While normal text is 
`font-size: var(--bs-body-font-size);`
text in shared content is
`font-size: 0.95rem;`

"20 days ago" (highlighted in the screenshot by selecting it) is white text on bright gray background, thus not visible. 

The bright gray background (for shared content) is too close to white (background for normal content), it should be either the same white or a more distinct color. 

The bright gray and darker gray backgrounds have round corners, while i.e. [quote][/quote] text has no round corners. I think, it should be the same, no round corners would be best. 

I guess all schemes need this to be optimized. 

For example the vapor scheme

<img width="639" height="583" alt="Image" src="https://github.com/user-attachments/assets/8e77c68c-470b-4d11-b3ed-29ca22e19b22" />

where 

`color: var(--bs-body-color); `
inside the shared content is not seen well on 
`background-color: var(--bs-secondary-bg);`

**Comment by saiwal** [comment]
@kingemir should be fixed with fa7fb28

**Comment by kingemir** [comment]
Thanks for the update. 

But in brite scheme, these issues are still present

While normal links (i.e. Ema エマ in the screenshot) are 
`color: rgba(var(--bs-link-color-rgb), var(--bs-link-opacity, 1)); font-weight: bold !important; font-size: var(--bs-body-font-size);`
links within the shared content (i.e. UrsuUrsula) are 
`color: var(--bs-info); font-weight: 500; font-size: 0.95rem;`

While normal text is 
`font-size: var(--bs-body-font-size);`
text in shared content is
`font-size: 0.95rem;`

In vapor scheme, this issue is still present (change from secondary-bg to tertiary-bg didn't help anything): 

`color: var(--bs-body-color); `
inside the shared content is not seen well on 
`background-color: var(--bs-tertiary-bg);`

**Comment by saiwal** [comment]
Fixed the header link color to be consistent with content link color, and size of text to be same as other post text. Also vapor color is fixed for light mode which was not seen well.

**Comment by saiwal** [comment]
do both hubs have the latest theme updates on them? if not, that may be the reason, also it might be a caching issue. some css files are cached for upto a day.

**Comment by saiwal** [comment]
the border is back but is translucent now. :)

**Comment by kingemir** [comment]
> the border is back but is translucent now. :)

Thank you!
